name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format code
        run: bun run format

      - name: Lint code
        run: bun run lint

      - name: Type check
        run: bunx tsc --noEmit

      - name: Build
        run: bunx tsc
