name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format code
        run: bun run format

      - name: Lint code
        run: bun run lint

      - name: Type check
        run: bunx tsc --noEmit

      - name: Build
        run: bunx tsc

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install commitlint
        run: |
          bun add -d @commitlint/cli @commitlint/config-conventional

      - name: Print versions
        run: |
          git --version
          bun --version
          bunx commitlint --version

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bunx commitlint --from HEAD~1 --to HEAD --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: bunx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
